### ISSUE TITLE
Different color for keyboard action text

### ISSUE THREAD

**Issue by DatL4g** [dzirbel/compose-material-context-menu#3]
Please add a color value for the text like `Ctrl + C`, `Ctrl + V` etc.
Normally they are a little bit less visible in popup menus, so the "normal" text is black for example and the `Ctrl + C` is more like grey, in most applications.
I think it's the best way to separate the text from the actions

**Comment by dzirbel** [comment]
Good idea! I've added a field `ContextMenuColors.shortcutText` to allow this, and optional override per-item via field `ContextMenuIcon.OfShortcuts.color`, I hope that will work for you. I've left the default to match the text color since that appears to be the behavior in Material 2 and 3 menus (Material 3 specifies it as the "On surface variant" color, but the Compose Material colors don't yet support this field).
